version: "3.8"

# include:
#   - ./history4feed/docker-compose.yml
   
services:
    django:
        image: obstracts
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build: .
        command: >
                bash -c "
                    python obstracts/cjob/arango_view_helper.py &&
                    python manage.py makemigrations &&
                            python manage.py migrate &&
                            gunicorn obstracts.wsgi:application  --reload --bind 0.0.0.0:8001
                    " 
        volumes:
            - .:/usr/src/app/
        ports:
            - 8001:8001
        environment:
            - DJANGO_SETTINGS_MODULE=obstracts.settings
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER_URL=redis://redis:6379/10
            - POSTGRES_HOST=pgdb
        env_file:
            - ./.env
        depends_on:
            - celery

    celery:
        image: obstracts
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build: .
        command: >
                bash -c "
                  celery -A obstracts.cjob worker -l INFO
                  "
        volumes:
            - .:/usr/src/app
        environment:
            - POSTGRES_HOST=pgdb
            - DJANGO_SETTINGS_MODULE=obstracts.settings
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER_URL=redis://redis:6379/10
            - result_backend=redis://redis:6379/11
        env_file:
            - ./.env
        depends_on:
            pgdb:
                condition: service_healthy
            redis:
                condition: service_started

    scheduler:
        extends: celery
        command: >
                bash -c "
                celery -A obstracts.cjob beat -l INFO 
                "

    pgdb:
        image: postgres
        env_file:
          - ./.env

        volumes:
            - pgdata:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 10s
    redis:
        image: "redis:alpine"

volumes:
    pgdata: