# Generated by Django 5.0.6 on 2024-07-12 17:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('extractions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='extraction id(s)', size=None)),
                ('whitelists', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='whitelist id(s)', size=None)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='alias id(s)', size=None)),
                ('relationship_mode', models.CharField(choices=[('ai', 'AI Relationship'), ('standard', 'AI Relationship')], default='standard', max_length=20)),
                ('prettify_with_ai', models.BooleanField(default=False)),
                ('extract_text_from_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('feed_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('retrieving', 'Retrieving'), ('processing', 'Processing'), ('processed', 'Processed'), ('retrieve_failed', 'Retrieve Failed')], default='retrieving', max_length=20)),
                ('h4f_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('item_count', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('failed_processes', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.profile')),
            ],
        ),
    ]
