# Generated by Django 5.1.2 on 2025-02-18 11:09

import django.db.models.deletion
import obstracts.server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogesec_stixifier', '0001_initial'),
        ('history4feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedProfile',
            fields=[
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='obstracts_feed', serialize=False, to='history4feed.feed')),
                ('collection_name', models.CharField(max_length=200)),
                ('last_run', models.DateTimeField(null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogesec_stixifier.profile')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='obstracts_post', serialize=False, to='history4feed.post')),
                ('markdown_file', models.FileField(null=True, upload_to=obstracts.server.models.upload_to_func)),
                ('summary', models.CharField(max_length=65535, null=True)),
                ('feed', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='obstracts.feedprofile')),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='dogesec_stixifier.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=obstracts.server.models.upload_to_func)),
                ('name', models.CharField(max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='obstracts.file')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('history4feed_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='obstracts_job', related_query_name='job_id', serialize=False, to='history4feed.job')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('retrieving', 'Retrieving'), ('in-queue', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('processing_failed', 'Process Failed'), ('retrieve_failed', 'Retrieve Failed')], default='retrieving', max_length=20)),
                ('processed_items', models.IntegerField(default=0)),
                ('failed_processes', models.IntegerField(default=0)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obstracts.feedprofile')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogesec_stixifier.profile')),
            ],
        ),
    ]
