# Generated by Django 5.1.6 on 2025-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ai_describes_incident',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ai_incident_classification',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='ai_incident_summary',
            field=models.CharField(default=None, max_length=65535, null=True),
        ),
    ]
