# Generated by Django 5.1.3 on 2024-11-11 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_settings_extractions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_settings_relationships',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extractions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whitelists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
    ]
