# Generated by Django 5.0.6 on 2024-07-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='feed_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='profile',
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('retrieving', 'Retrieving'), ('processing', 'Processing'), ('processed', 'Processed'), ('processing_failed', 'Process Failed'), ('retrieve_failed', 'Retrieve Failed')], default='retrieving', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_mode',
            field=models.CharField(choices=[('ai', 'AI Relationship'), ('standard', 'Standard Relationship')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=200)),
                ('last_run', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=1000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.profile')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.feedprofile'),
        ),
    ]
