# Generated by Django 5.0.8 on 2024-11-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_profile_ai_settings_extractions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whitelists',
        ),
    ]
