# Generated by Django 5.1.6 on 2025-03-21 11:32

import django.contrib.postgres.fields
from django.db import migrations, models
import ast


def convert_to_list(apps, schema_editor):
    File = apps.get_model('obstracts', 'File')
    for file in File.objects.all():
        if not file.old_incident_classification:
            file.ai_incident_classification = []
        elif file.old_incident_classification.startswith('['):
            file.ai_incident_classification = ast.literal_eval(file.old_incident_classification)
        else:
            file.ai_incident_classification = [file.old_incident_classification]
        file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0002_file_ai_describes_incident_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='ai_incident_classification',
            new_name='old_incident_classification',
        ),
        migrations.AddField(
            model_name='file',
            name='ai_incident_classification',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=256, null=True), blank=True, null=True, size=None),
        ),
        migrations.RunPython(
            code=convert_to_list,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='file',
            name='old_incident_classification',
        ),
    ]
