# Generated by Django 5.0.6 on 2024-07-29 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_job_feed_id_remove_job_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, help_text='alias id(s)', size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whitelists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, help_text='whitelist id(s)', size=None),
        ),
    ]
