# Generated by Django 5.1.6 on 2025-05-01 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0003_alter_file_ai_incident_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
    ]
