# Generated by Django 5.0.6 on 2024-07-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_profile_aliases_alter_profile_whitelists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='h4f_status',
            new_name='history4feed_status',
        ),
    ]
