# Generated by Django 5.1.6 on 2025-05-01 13:10

import typing
from django.db import migrations, models
from django.db.models import OuterRef, Subquery, F, Q

if typing.TYPE_CHECKING:
    from ..models import File, Job
    from history4feed.app.models import FulltextJob


def set_processed_flag(apps, schema_editor):
    FileModel: File = apps.get_model('obstracts', 'File')
    FulltextJobModel: FulltextJob = apps.get_model('history4feed', 'FulltextJob')
    JobModel: Job = apps.get_model('obstracts', 'Job')
    queryset = FileModel.objects.all()
    for file in queryset:
        ftjob = FulltextJobModel.objects.filter(post_id=file.pk).order_by("-job__run_datetime").first()
        job = JobModel.objects.get(pk=ftjob.job_id)
        file.processed = (job.state == 'processed')
        file.save(update_fields=['processed'])

class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0004_job_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_processed_flag, reverse_code=migrations.RunPython.noop),
    ]
