# Generated by Django 5.0.6 on 2024-07-31 11:21

from django.db import migrations, models
from obstracts.server.models import Profile as ProfileType
from django.db.models import Count, Index

import logging
logging.basicConfig(level=logging.INFO)


def update_profile_names(apps, schema_editor):
    Profile: ProfileType = apps.get_model('server', 'Profile')
    dupes = [v['name'] for v in Profile.objects.values('name').annotate(name_count=Count('id')).filter(name_count__gt=1)]
    profiles = Profile.objects.filter(name__in=dupes)

    for index, profile in enumerate(profiles, start=1):
        profile.name = f"{profile.name} {index} (autorenamed)"
    Profile.objects.bulk_update(profiles, ['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_h4f_status_job_history4feed_status'),
    ]

    operations = [
        migrations.RunPython(update_profile_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
