# Generated by Django 5.0.6 on 2024-07-31 11:21

from django.db import migrations, models
from obstracts.server.models import Profile as ProfileType
from django.db.models import Count, Index


def update_profile_names(apps, schema_editor):
    Profile: ProfileType = apps.get_model('server', 'Profile')
    # profiles = Profile.objects.all()
    profiles = Profile.objects.annotate(name_count=Count('name')).filter(name_count__gt=1)

    for index, profile in enumerate(profiles, start=1):
        profile.name = f"{profile.name}_{index}"
    
    Profile.objects.bulk_update(profiles, ['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_h4f_status_job_history4feed_status'),
    ]

    operations = [
        migrations.RunPython(update_profile_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
