# Generated by Django 5.0.6 on 2024-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_h4f_status_job_history4feed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
