# Generated by Django 5.1.6 on 2025-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0005_file_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('retrieving', 'Retrieving'), ('in-queue', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('processing_failed', 'Process Failed'), ('retrieve_failed', 'Retrieve Failed')], default='retrieving', max_length=20),
        ),
    ]
