# Generated by Django 5.1.6 on 2025-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0006_alter_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='txt2stix_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
