# Generated by Django 5.0.8 on 2024-11-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_file_ai_summary_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_summary_provider',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
