# Generated by Django 5.0.6 on 2024-08-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_profile_aliases_alter_profile_extractions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prettify_with_ai',
        ),
    ]
