# Generated by Django 5.2.3 on 2025-06-12 13:28

import obstracts.server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0007_file_txt2stix_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=obstracts.server.models.upload_to_func),
        ),
    ]
