# Generated by Django 5.2.1 on 2025-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0008_file_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('retrieving', 'Retrieving'), ('in-queue', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('processing_failed', 'Process Failed'), ('retrieve_failed', 'Retrieve Failed')], default='retrieving', max_length=20),
        ),
    ]
