# Generated by Django 5.0.6 on 2024-09-04 16:07

import django.contrib.postgres.fields
import obstracts.server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('post_id', models.UUIDField(primary_key=True, serialize=False)),
                ('markdown_file', models.FileField(null=True, upload_to=obstracts.server.models.upload_to_func)),
                ('extra_files', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=obstracts.server.models.upload_to_func), default=list, size=None)),
            ],
        ),
    ]
