# Generated by Django 5.0.10 on 2025-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignore_extraction_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
