# Generated by Django 5.2.1 on 2025-07-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0009_alter_file_markdown_file_alter_file_pdf_file_and_more'),
        ('obstracts', '0009_alter_job_state'),
    ]

    operations = [
    ]
