# Generated by Django 5.0.6 on 2024-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='history4feed_job',
            field=models.JSONField(null=True),
        ),
    ]
