# Generated by Django 5.2.1 on 2025-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0010_merge_20250725_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completion_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
