# Generated by Django 5.0.6 on 2024-10-01 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_job_history4feed_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.profile'),
        ),
    ]
