# Generated by Django 5.0.6 on 2024-10-02 14:37

import django.db.models.deletion
import obstracts.server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_job_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extra_files',
        ),
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=obstracts.server.models.upload_to_func)),
                ('name', models.CharField(max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='server.file')),
            ],
        ),
    ]
