# Generated by Django 5.2.1 on 2025-10-21 12:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


def populate_job_id(apps, schema_editor):
    Job = apps.get_model("obstracts", "Job")
    # Use .iterator() for large querysets to reduce memory usage
    for job in Job.objects.using(schema_editor.connection.alias).iterator():
        job.id_new = job.history4feed_job_id
        job.save(update_fields=["id_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts", "0011_job_completion_time"),
        ("history4feed", "0001_initial"),
    ]

    operations = [
        # Django doesn't support changing a primary key in a single step.
        # We need to do this in several steps:
        # 1. Add a new field for the future primary key, nullable for now.
        migrations.AddField(
            model_name="job",
            name="id_new",
            field=models.UUIDField(null=True),
        ),
        # 2. Populate the new field with the values from the old primary key.
        migrations.RunPython(populate_job_id, reverse_code=migrations.RunPython.noop),
        # 3. Make the new field unique and non-nullable.
        migrations.AlterField(
            model_name="job",
            name="id_new",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        # 4. Remove the primary key constraint from the old 'history4feed_job' field.
        migrations.AlterField(
            model_name="job",
            name="history4feed_job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="history4feed.job",
                related_name="obstracts_job",
                related_query_name="job_id",
            ),
        ),
        # 5. Rename our new field to 'id' and make it the primary key.
        migrations.RenameField(model_name="job", old_name="id_new", new_name="id"),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False, editable=False),
        ),
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[("feed_index", "Feed Index"), ("pdf_index", "Pdf Index")],
                default="feed_index",
                max_length=20,
            ),
        ),
        # allow null
        migrations.AlterField(
            model_name="job",
            name="history4feed_job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="history4feed.job",
                related_name="obstracts_job",
                related_query_name="job_id",
                null=True,
            ),
        ),
    ]
