# Generated by Django 5.0.6 on 2024-10-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_file_extra_files_fileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='defang',
            field=models.BooleanField(default=True),
        ),
    ]
