# Generated by Django 5.2.7 on 2025-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0012_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedprofile',
            name='pdfshift_cookie_settings',
            field=models.CharField(choices=[('disable_all_js', 'Disable All Js'), ('remove_cookie_elements', 'Remove Cookie Elements')], default='disable_all_js'),
        ),
    ]
