# Generated by Django 5.2.8 on 2025-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0013_feedprofile_pdfshift_cookie_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('feed_index', 'Feed Index'), ('pdf_index', 'Pdf Index'), ('sync-vulnerabilities', 'Sync Vulnerabilities')], default='feed_index', max_length=64),
        ),
    ]
