# Generated by Django 5.2.8 on 2026-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0014_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('feed_index', 'Feed Index'), ('pdf_index', 'Pdf Index'), ('sync-vulnerabilities', 'Sync Vulnerabilities'), ('reprocess-posts', 'Reprocess Posts')], default='feed_index', max_length=64),
        ),
    ]
