# Generated by Django 5.2.11 on 2026-03-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
        ('obstracts', '0016_objectvalue_jsonb_values_concat_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='embedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.documentembedding'),
        ),
    ]
