# Generated by Django 5.2.11 on 2026-03-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
        ('obstracts', '0016_objectvalue_jsonb_values_concat_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='embedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to='classifier.documentembedding'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('feed_index', 'Feed Index'), ('pdf_index', 'Pdf Index'), ('sync-vulnerabilities', 'Sync Vulnerabilities'), ('reprocess-posts', 'Reprocess Posts'), ('build-embeddings', 'Build Embeddings'), ('build-clusters', 'Build Clusters')], default='feed_index', max_length=64),
        ),
    ]
