# Generated by Django 5.2.11 on 2026-03-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0017_file_embedding_alter_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectvalue',
            old_name='ttp_type',
            new_name='knowledgebase',
        ),
    ]
