# Generated by Django 5.2.11 on 2026-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0018_rename_ttp_type_objectvalue_knowledgebase'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(fields=['stix_id', 'modified'], name='obstracts_s_stix_id_modified'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(fields=['type', 'stix_id'], name='obstracts_ov_type_stix_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(fields=['knowledgebase', 'stix_id'], name='obstracts_ov_kbase_stix_idx'),
        ),
    ]
