# Generated by Django 5.2.12 on 2026-03-31 12:53

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0018_rename_ttp_type_objectvalue_knowledgebase'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_values_concat(j jsonb)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT string_agg(value, ' ')
                FROM jsonb_each_text(j)
            $$;
            """,
            # reverse_sql="DROP FUNCTION IF EXISTS jsonb_values_concat(jsonb);",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_first_value(j jsonb)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT value
                FROM jsonb_each_text(j)
                LIMIT 1
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS jsonb_first_value(jsonb);",
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_values_list(j jsonb)
            RETURNS text[]
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT array_agg(LOWER(value))
                FROM jsonb_each_text(j)
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS jsonb_values_list(jsonb);",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX ctx_values_concat_idx
            ON obstracts_objectvalue
            USING gin ((jsonb_values_concat(values)) gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS ctx_values_concat_idx;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX ctx_values_list_idx
            ON obstracts_objectvalue
            USING gin (jsonb_values_list(values) array_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS ctx_values_list_idx;",
        ),
    ]
