# Generated by Django 5.2.11 on 2026-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0020_objectvalue_obstracts_s_stix_id_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectvalue',
            name='is_dupe',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
