# Generated by Django 5.2.11 on 2026-04-03 13:46

import django.contrib.postgres.fields
import django.db.models.fields.json
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0021_objectvalue_is_dupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectvalue',
            name='value',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_s_stix_id_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_s_stix_id_modified',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_type_stix_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_kbase_stix_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_first_value_idx',
        ),
        migrations.AddField(
            model_name='objectvalue',
            name='values_concat',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), function='jsonb_values_concat'), null=True, output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='objectvalue',
            name='values_list',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), function='jsonb_values_list'), null=True, output_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
        ),
        migrations.AlterField(
            model_name='objectvalue',
            name='is_dupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='objectvalue',
            name='knowledgebase',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='objectvalue',
            name='type',
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'stix_id'], name='obstracts_ov_type_stix_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'knowledgebase'], name='obstracts_ov_kbase_c_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'knowledgebase'], name='obstracts_ov_kbase_m_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'type'], name='obstracts_ov_created_type_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'type'], name='obstracts_ov_modified_type_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('kb_type', 'values'), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_kb_type_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('created'), django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('kb_id', 'values')), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_kb_id_cidx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('modified'), django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('kb_id', 'values')), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_kb_id_midx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('values_concat'), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_values_concat_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('values_concat'), models.F('knowledgebase'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_values_c_kbidx'),
        ),
    ]
