# Generated by Django 5.2.11 on 2026-04-07 11:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0022_remove_objectvalue_obstracts_s_stix_id_type_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectvalue',
            name='values_concat',
        ),
        migrations.AddField(
            model_name='objectvalue',
            name='values_concat',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Lower(models.Func(models.F('values'), function='jsonb_values_concat')), null=True, output_field=models.TextField()),
        ),
    ]
