# Generated by Django 5.2.11 on 2026-04-10

from django.db import migrations, models
import django.contrib.postgres.search


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts", "0023_alter_objectvalue_values_concat"),
        ('history4feed', '0011_post_h4f_pubdate_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_search'], name='obstracts_file_text_search_idx'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION obstracts_file_set_text_search()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                post_title text;
                post_description text;
            BEGIN
                SELECT p.title, p.description
                INTO post_title, post_description
                FROM history4feed_post p
                WHERE p.id = NEW.post_id;

                NEW.text_search := to_tsvector(
                    COALESCE(post_title, '') || ' ' ||
                    COALESCE(post_description, '') || ' ' ||
                    COALESCE(NEW.summary, '') || ' ' ||
                    COALESCE(NEW.ai_incident_summary, '')
                );

                RETURN NEW;
            END;
            $$;

            DROP TRIGGER IF EXISTS obstracts_file_text_search_trigger ON obstracts_file;
            CREATE TRIGGER obstracts_file_text_search_trigger
            BEFORE INSERT OR UPDATE OF post_id, summary, ai_incident_summary
            ON obstracts_file
            FOR EACH ROW
            EXECUTE FUNCTION obstracts_file_set_text_search();

            UPDATE obstracts_file f
            SET text_search = to_tsvector(
                COALESCE(p.title, '') || ' ' ||
                COALESCE(p.description, '') || ' ' ||
                COALESCE(f.summary, '') || ' ' ||
                COALESCE(f.ai_incident_summary, '')
            )
            FROM history4feed_post p
            WHERE p.id = f.post_id;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS obstracts_file_text_search_trigger ON obstracts_file;
            DROP FUNCTION IF EXISTS obstracts_file_set_text_search();
            """,
        ),

        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['processed', 'ai_describes_incident', 'post_id'], name='obstracts_file_processed_idx'),
        ),
    ]
