# Generated by Django 5.2.11 on 2026-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('obstracts', '0024_file_text_search_with_trigger'),
    ]
    atomic = False

    operations = [
        migrations.RunSQL(
            "VACUUM ANALYZE;",
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
