# Generated by Django 5.2.11 on 2026-04-02 14:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0025_run_vacuum_analyze'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS ctx_values_list_idx;
            DROP INDEX IF EXISTS obstracts_ov_values_list_idx;
            CREATE INDEX obstracts_ov_values_list_idx
            ON obstracts_objectvalue
            USING gin (values_list array_ops, type gin_trgm_ops, knowledgebase gin_trgm_ops) WHERE NOT is_dupe;
            """,
            reverse_sql="",
        ),

        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS ctx_values_concat_idx;
            DROP INDEX IF EXISTS obstracts_ov_values_concat_idx;
            CREATE INDEX obstracts_ov_values_concat_idx
            ON obstracts_objectvalue
            USING gin (values_concat gin_trgm_ops, type gin_trgm_ops, knowledgebase gin_trgm_ops) WHERE NOT is_dupe;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_sort_value(j jsonb, extra_text text)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT SUBSTR(LOWER(value), 1, 32) || '+' || extra_text
                FROM jsonb_each_text(j)
                LIMIT 1
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
