# Generated by Django 5.2.11 on 2026-05-08 14:04

import django.db.models.fields.json
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0026_add_index_on_values_list'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_kbase_c_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_kbase_m_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_created_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_modified_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_kb_id_cidx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_kb_id_midx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_values_concat_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectvalue',
            name='obstracts_ov_values_c_kbidx',
        ),
        ## add field
        migrations.AddField(
            model_name='objectvalue',
            name='values_sort',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), django.db.models.functions.comparison.Cast(models.F('id'), models.TextField()), function='jsonb_sort_value'), null=True, output_field=models.CharField(max_length=48)),
        ),
        ## add id to all sort fields for keyset pagination
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'id', 'knowledgebase'], name='obstracts_ov_kbase_c_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'id', 'knowledgebase'], name='obstracts_ov_kbase_m_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'id', 'type'], name='obstracts_ov_created_type_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'id', 'type'], name='obstracts_ov_modified_type_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('created'), models.F('id'), django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('kb_id', 'values')), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_kb_id_cidx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('modified'), models.F('id'), django.db.models.functions.text.Upper(django.db.models.fields.json.KeyTextTransform('kb_id', 'values')), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_kb_id_midx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('values_sort'), models.F('type'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_values_concat_idx'),
        ),
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('values_sort'), models.F('knowledgebase'), condition=models.Q(('is_dupe', False)), name='obstracts_ov_values_c_kbidx'),
        ),
    ]
