# Generated by Django 5.2.11 on 2026-05-13 14:58

from django.db import migrations, models

def backfill_has_h4f_failures(apps, schema_editor):
    """
    """
    from obstracts.server.models import Job as JobType
    Job: type[JobType] = apps.get_model('obstracts', 'Job')
    jobs = Job.objects.all().order_by('-created').prefetch_related('history4feed_job')[:1000]
    updated_jobs = []
    for job in jobs:
        if job.history4feed_job:
            job.has_h4f_failures = job.history4feed_job.fulltext_jobs.filter(status__in=['timed_out', 'failed']).exists()
            updated_jobs.append(job)
    Job.objects.bulk_update(updated_jobs, ['has_h4f_failures'])



class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0027_remove_objectvalue_obstracts_ov_kbase_c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_h4f_failures',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=backfill_has_h4f_failures,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
