# Generated by Django 5.2.11 on 2026-05-21 14:56

from django.db import migrations, models


def rename_sync_tasks(apps, schema_editor):
    Job = apps.get_model('obstracts', 'Job')
    Job.objects.filter(type='sync-vulnerabilities').update(type='sync-knowledgebase', extra=dict(knowledgebase='cve'))



class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0028_job_has_h4f_failures'),
    ]

    operations = [
        migrations.RunPython(
            rename_sync_tasks,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('feed_index', 'Feed Index'), ('pdf_index', 'Pdf Index'), ('sync-knowledgebase', 'Sync Knowledgebase'), ('reprocess-posts', 'Reprocess Posts'), ('build-embeddings', 'Build Embeddings'), ('build-clusters', 'Build Clusters')], default='feed_index', max_length=64),
        ),
    ]
