# Generated by Django 5.2.11 on 2026-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0029_alter_job_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objectvalue',
            index=models.Index(models.F('file_id'), models.F('knowledgebase'), name='obstracts_kb_stats'),
        ),
    ]
