# Generated by Django 5.2.11 on 2026-06-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts", "0030_objectvalue_obstracts_kb_stats"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="objectvalue",
                    name="file",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="object_values",
                        to="obstracts.file",
                    ),
                )
            ],
        ),
    ]
