# Generated by Django 5.2.11 on 2026-06-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history4feed', '0012_post_h4f_feed_pk'),
        ('obstracts', '0031_alter_objectvalue_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['feed_id', 'post_id'], name='obstracts_file_feed_id_idx'),
        ),
        migrations.AlterField(
            model_name='objectvalue',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_values', to='obstracts.file'),
        ),
    ]
