# Generated by Django 5.2.11 on 2026-07-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstracts', '0032_file_obstracts_file_feed_id_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedprofile',
            name='admiralty_source_reliability',
            field=models.CharField(choices=[('A', 'A - Completely reliable'), ('B', 'B - Usually reliable'), ('C', 'C - Fairly reliable'), ('D', 'D - Not usually reliable'), ('E', 'E - Unreliable'), ('F', 'F - Reliability cannot be judged')], default=None, max_length=1, null=True),
        ),
    ]
