from rest_framework import serializers
from .models import Profile, Job, FileImage
from drf_spectacular.utils import extend_schema_serializer, extend_schema_field
from django.utils.translation import gettext_lazy as _


class ProfileSerializer(serializers.ModelSerializer):
    id = serializers.UUIDField(read_only=True)

    class Meta:
        model = Profile
        fields = "__all__"


class T2SSerializer(serializers.Serializer):
    id = serializers.CharField()
    name = serializers.CharField()
    type = serializers.CharField()
    description = serializers.CharField()
    notes = serializers.CharField()
    file = serializers.CharField()
    created = serializers.CharField()
    modified = serializers.CharField()
    created_by = serializers.CharField()
    version = serializers.CharField()
    stix_mapping = serializers.CharField()


class JobSerializer(serializers.ModelSerializer):
    feed_id = serializers.PrimaryKeyRelatedField(read_only=True, source='feed')
    profile_id = serializers.PrimaryKeyRelatedField(read_only=True, source='profile')
    class Meta:
        model = Job
        # fields = "__all__"
        exclude = ["feed", "profile"]


class FeedSerializer(serializers.Serializer):
    profile_id = serializers.PrimaryKeyRelatedField(queryset=Profile.objects, error_messages={
        'required': _('This field is required.'),
        'does_not_exist': _('Invalid profile with id "{pk_value}" - object does not exist.'),
        'incorrect_type': _('Incorrect type. Expected profile id (uuid), received {data_type}.'),
    })
    url = serializers.URLField(help_text="The URL of the RSS or ATOM feed")
    include_remote_blogs = serializers.BooleanField(help_text="", default=False, required=False)

class PatchFeedSerializer(FeedSerializer):
    url = None

class PatchPostSerializer(serializers.Serializer):
    profile_id = serializers.PrimaryKeyRelatedField(queryset=Profile.objects, error_messages={
        'required': _('This field is required.'),
        'does_not_exist': _('Invalid profile with id "{pk_value}" - object does not exist.'),
        'incorrect_type': _('Incorrect type. Expected profile id (uuid), received {data_type}.'),
    })

class ImageSerializer(serializers.ModelSerializer):
    url = serializers.SerializerMethodField()
    class Meta:
        model = FileImage
        fields = ["name", "url"]

    @extend_schema_field(serializers.CharField())
    def get_url(self, instance):
        request = self.context.get('request')
        if instance.file and hasattr(instance.file, 'url'):
            photo_url = instance.file.url
            return request.build_absolute_uri(photo_url)
        return None

class H4fFeedSerializer(serializers.Serializer):
    def get_schema(self):
        true = True
        return {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid",
                        "readOnly": true,
                        "description": "UUID of feed generated by history4feed"
                    },
                    "job_id": {
                        "type": "string",
                        "format": "uuid",
                        "readOnly": true,
                        "description": "only returns with POST /feeds/"
                    },
                    "job_state": {
                        "type": "string",
                        "readOnly": true,
                        "description": "only returns with POST /feeds/"
                    },
                    "count_of_posts": {
                        "type": "integer",
                        "readOnly": true,
                        "description": "Number of posts in feed"
                    },
                    "title": {
                        "type": "string",
                        "readOnly": true,
                        "description": "found in the <channel> of RSS output. Is always kept up to date with the latest feed import values for this property."
                    },
                    "description": {
                        "type": "string",
                        "readOnly": true,
                        "description": "found in the <channel> of RSS output. Is always kept up to date with the latest feed import values for this property."
                    },
                    "url": {
                        "type": "string",
                        "format": "uri",
                        "description": "\nThe URL of the RSS or ATOM feed\n\nNote this will be validated to ensure the feed is in the correct format.\n",
                        "maxLength": 1000
                    },
                    "earliest_item_pubdate": {
                        "type": "string",
                        "format": "date-time",
                        "readOnly": true,
                        "nullable": true,
                        "description": "pubdate of earliest post"
                    },
                    "latest_item_pubdate": {
                        "type": "string",
                        "format": "date-time",
                        "readOnly": true,
                        "nullable": true,
                        "description": "pubdate of latest post"
                    },
                    "datetime_added": {
                        "type": "string",
                        "format": "date-time",
                        "readOnly": true,
                        "description": "date feed entry was added to database"
                    },
                    "feed_type": {
                        "type": "string",
                        "readOnly": true,
                        "description": "type of feed"
                    },
                    "include_remote_blogs": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "count_of_posts",
                    "datetime_added",
                    "description",
                    "earliest_item_pubdate",
                    "feed_type",
                    "id",
                    "job_id",
                    "job_state",
                    "latest_item_pubdate",
                    "title",
                    "url"
                ]
            }


class H4fPostSerializer(serializers.Serializer):
    def get_schema(self):
        true = True
        return {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "description": "UUID of items generated by history4feed",
                },
                "datetime_added": {
                    "type": "string",
                    "format": "date-time",
                    "readOnly": true,
                },
                "datetime_updated": {
                    "type": "string",
                    "format": "date-time",
                    "readOnly": true,
                },
                "title": {
                    "type": "string",
                    "description": "found in the <item> element of feed output",
                    "maxLength": 1000,
                },
                "description": {
                    "type": "string",
                    "description": "found in the <item> element of feed output",
                    "maxLength": 2097152,
                },
                "link": {
                    "type": "string",
                    "format": "uri",
                    "description": "link to full article. found in the <item> element of feed output",
                    "maxLength": 1000,
                },
                "pubdate": {
                    "type": "string",
                    "format": "date-time",
                    "description": "date of publication.",
                },
                "author": {
                    "type": "string",
                    "description": "author of the post",
                    "maxLength": 1000,
                },
                "is_full_text": {
                    "type": "boolean",
                    "description": "if full text has been retrieved",
                },
                "content_type": {
                    "type": "string",
                    "description": "content type of the description",
                    "maxLength": 200,
                },
                "categories": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "categories of the post",
                },
            },
            "required": [
                "author",
                "categories",
                "datetime_added",
                "datetime_updated",
                "link",
                "pubdate",
                "title",
            ],
        }


class ErrorSerializer(serializers.Serializer):
    message = serializers.CharField(required=True)
    code    = serializers.IntegerField(required=True)
    details = serializers.DictField(required=False)