name: Auto PR to Staging

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy commit to trigger PR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Sync main to staging"
      
      - name: Create PR from main to staging
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: staging
          title: "Auto PR from main to staging"
          body: "This PR was automatically created to sync changes from `main` to `staging`."
          branch: auto-pr-main-to-staging
          delete-branch: true