name: update requirements

permissions:
  contents: write
  
on: [workflow_call]

jobs:
    update-requirements:
        runs-on: ubuntu-latest
        environment: test_pipeline
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - name: Update requirements
              run: |
                pip install pip-tools
                pip-compile -o requirements.txt requirements.in pyproject.toml --upgrade
            
            - name: Push if update exists
              run: |
                git config --local user.name "github-actions[bot]"
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git add requirements.txt requirements.in
                if [ -z "$(git status --porcelain)" ]; then
                    echo "No changes to commit"
                    exit 0
                fi
                git remote set-url origin "https://oauth2:${{github.token}}@github.com/${{github.repository}}.git"
                git commit -m 'update requirements [bot]'
                git push origin ${{ github.head_ref }}
